// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7ueuQVG9VOCH8_N2y0-OiC4iWEkBrsw',
    appId: '1:950210039144:web:17840c484f74ed17eb1add',
    messagingSenderId: '950210039144',
    projectId: 'recipebuddy-48b9f',
    authDomain: 'recipebuddy-48b9f.firebaseapp.com',
    storageBucket: 'recipebuddy-48b9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf7-l1sXqjtG6SfvNst9Vy4WsPOAUkuc',
    appId: '1:950210039144:android:1b83d4d78b0df495eb1add',
    messagingSenderId: '950210039144',
    projectId: 'recipebuddy-48b9f',
    storageBucket: 'recipebuddy-48b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPh-2x_1OSUxcA65QyLVkl5dLOWaJBz0',
    appId: '1:950210039144:ios:cafd6a1c0431d4e4eb1add',
    messagingSenderId: '950210039144',
    projectId: 'recipebuddy-48b9f',
    storageBucket: 'recipebuddy-48b9f.firebasestorage.app',
    iosBundleId: 'com.example.recipeBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJPh-2x_1OSUxcA65QyLVkl5dLOWaJBz0',
    appId: '1:950210039144:ios:cafd6a1c0431d4e4eb1add',
    messagingSenderId: '950210039144',
    projectId: 'recipebuddy-48b9f',
    storageBucket: 'recipebuddy-48b9f.firebasestorage.app',
    iosBundleId: 'com.example.recipeBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR7ueuQVG9VOCH8_N2y0-OiC4iWEkBrsw',
    appId: '1:950210039144:web:db51e08b6264f801eb1add',
    messagingSenderId: '950210039144',
    projectId: 'recipebuddy-48b9f',
    authDomain: 'recipebuddy-48b9f.firebaseapp.com',
    storageBucket: 'recipebuddy-48b9f.firebasestorage.app',
  );
}
